package:
  name: ase-extensions
  version: 0.1

source:
  git_url: https://github.com/Clyde-fare/ase_extensions.git

build:
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - ase
    - molmod
    - paramiko
